#!/bin/bash

for REPO in */*/ freq/freqtrade_official/*/ freq/freqtrade_official/other_bots/*/*/ freq/freqtrade_official/other_bots/pycryptobot/; do
    git -C "$REPO" rev-parse --is-inside-work-tree >/dev/null 2>&1 || continue
    echo This is "$REPO"
    [[ -d $REPO ]] || continue
    git -C "$REPO" remote -v
    git -C "$REPO" rev-list --count HEAD # or branch name
    echo
    echo
done
