#!/bin/bash

# set -x

for REPO in */*/ freq/freqtrade_official/*/ freq/freqtrade_official/other_bots/*/*/ freq/freqtrade_official/other_bots/pycryptobot/; do
    [[ -d $REPO ]] || continue
    git -C "$REPO" rev-parse --is-inside-work-tree >/dev/null 2>&1 || continue
    git -C "$REPO" fetch --all --prune --tags
done
