#!/bin/bash
#grub
sudo xed /etc/default/grub # Look for the GRUB_TIMEOUT change value to 0
# change kernel parameters, this is GRUB_CMDLINE_LINUX_DEFAULT="quiet elevator=deadline rcutree.rcu_idle_gp_delay=1 rootflags=data=writeback"
sudo update-grub


#swappiness
sudo xed /etc/sysctl.conf
vm.swappiness=10 # add lines
vm.vfs_cache_pressure=50
vm.dirty_background_bytes=16777216
vm.dirty_bytes=50331648


#deprecated initv
#run boot processes in paralle
#sudo xed /etc/init.d/rc
# look for CONCURRENCY=none, change none to shell or makefile


#Trim StartUp
cd /etc/xdg/autostart
sudo sed --in-place 's/NoDisplay=true/NoDisplay=false/g' *.desktop # to see services
#Disable cups, mysql, apache2
sudo status cups
sudo sh -c "echo 'manual' > /etc/init/cups.override"


#Remove language related ign from apt-get update:
sudo xed /etc/apt/apt.conf.d/00aptitude
Acquire::Languages "none"; #add this line


sudo xed /etc/fstab
#replace options with noatime,nodiratime,errors=remount-ro,data=writeback
#load in RAM
tmpfs /var/tmp tmpfs defaults,noatime,nosuid,nodev,noexec,mode=1777,size=256M 0 0
tmpfs /var/lock tmpfs defaults,noatime,nosuid,nodev,noexec,mode=1777,size=256M 0 0
tmpfs /var/run tmpfs defaults,noatime,nosuid,nodev,noexec,mode=1777,size=256M 0 0
tmpfs /run/shm tmpfs defaults,noatime,nosuid,nodev,noexec,mode=1777,size=256M 0 0


#installs, deletes
#repos - python, (gsm)kdeconnect, kernel, guake(source code pro + syphonic colors), equaliser
sudo add-apt-repository ppa:deadsnakes/ppa
sudo add-apt-repository ppa:varlesh-l/indicator-kdeconnect
sudo add-apt-repository ppa:damentz/liquorix
sudo add-apt-repository ppa:nilarimogard/webupd8
sudo add-apt-repository ppa:gezakovacs/ppa
#sound compressor
#https://askubuntu.com/questions/95716/automatically-adjust-the-volume-based-on-content
#sublime
wget -qO - https://download.sublimetext.com/sublimehq-pub.gpg | sudo apt-key add -
echo "deb https://download.sublimetext.com/ apt/stable/" | sudo tee /etc/apt/sources.list.d/sublime-text.list && sudo apt-get update

sudo apt-get install alarm-clock-applet linux-image-liquorix-amd64 linux-headers-liquorix-amd64 gparted unrar p7zip-full pavucontrol paprefs vlc guake youtube-dl bash-completion preload ureadahead sublime-text neovim python3-venv python3-pip python-pip yapf python-pkg-resources python3-setuptools extlinux pulseaudio-equalizer=2.7.0.2-5~webupd8~xenial0 kdeconnect indicator-kdeconnect git
#snapd skypeforlinux gstreamer1.0-plugins tex-live rstudio mathematica spacemacs vsCode
python -m pip install wheel anaconda && python3 -m pip install wheel anaconda
sudo systemctl enable preload
#hold
sudo apt-mark hold linux-headers-liquorix-amd64
sudo apt-mark hold linux-image-liquorix-amd64
sudo apt-mark hold pulseaudio-equalizer
#purge
sudo apt-get purge rhythmbox* xplayer* thunderbird* orca* pidgin* linux-headers-4.15* linux-image-4.15* samba* tomboy* transmission* xed
#sudo apt-get purge #cups carefull
#finish
sudo apt-get upgrade && sudo apt-get autoremove && sudo apt-get autoclean && sudo updatedb


#bash completion
sudo gedit /etc/bash.bashrc
#Uncomment the following
#if [ -f /etc/bash_completion ]; then
# . /etc/bash_completion
#fi


#misc
#set up cron trim
#https://sites.google.com/site/easylinuxtipsproject/ssd#TOC-Still-relevant-for-Linux-Mint-19:-select-your-TRIM-method

#disable bling (desktop dependant), font size
#overclock nVidia http://www.techradar.com/news/computing/pc/how-to-speed-up-your-linux-machine-1078475

#boot, login, startx
lightDM login: /etc/lightDM/lightDM.conf
~/.xinitrc
sudo systemctl enable multi-user.target --force
sudo systemctl set-default multi-user.target

sudo add-apt-repository ppa:niko2040/e19
sudo add-apt install enlightenment
tixati; grip (display markdown server)
notebooks: cherrytree zim scite
expect (user input) tlc8.6 tlc-expect 
debootstrap 
mkusb mkusb-nox dus dusgui; unetbootin
gitkraken; sublime-merge
CLI browsers: lynx; w3m
kb-oriented-browsers: cutebrowser vimb
kb/cli-progrs: create_ap, ranger, vifm
cloud mount, net: gvfs gvfs-backends fuse gvfs-fuse samba opensshserver (apache2 php7.2)
news: new kernel; x11 replaced  (enlightenment)
commands: grep " install " /var/log/dpkg.log; history; sudo df --human-readable --print-type
